apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::410040182317:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1LR45SP4E0DOX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-11T01:30:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2020-12-11T01:30:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1650"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2097d882-c4bb-4096-bec7-0b74dfd4d25d
